import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ComingSoon from "react-coming-soon";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ComingSoon
          title="NEXTSHOP.com.bd is for sale!"
          subtitle="We quite our business before starting! This domain is for sale at only 1200$/0.1M BDT Contact here hi@nextshop.com.bd"
          image="https://i.ibb.co/ZTG6S4L/nxt.png"
          bgColor="#fafafa"
          textColor="#3f51b5"
          null
        />
      </main>
    </div>
  );
}
